apiVersion: v1
kind: ReplicationController
metadata:
  name: sample-rc-1
spec:
  replicas: 2
  selector:  
      app: myapp
      version: 2.7.01
  template:
    metadata:
      labels:
        app: myapp
        version: 2.7.01
    spec:
      containers:
      - name: deployment
        image: maha4iac/mymahalogin:1  
        ports:
        - containerPort: 8080  
